config/routes.rb
Rails.application.routes.draw do
  get 'pages/splash'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  devise_scope :user do
    authenticated :user do
      root :to => 'groups#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'pages#splash', as: :unauthenticated_root
    end
  end
  
  resources :groups, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :purchases
  end

  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_purchases, dependent: :destroy
  has_many :purchases, through: :group_purchases

  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group_purchase.rb
class GroupPurchase < ApplicationRecord
  belongs_to :group
  belongs_to :purchase
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :group_purchases, dependent: :destroy
  has_many :groups, through: :group_purchases

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      flash[:success] = 'Category created successfully!'
      redirect_to groups_path
    else
      flash.now[:error] = @group.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:success] = 'Category updated successfully!'
      redirect_to group_purchases_path(@group)
    else
      flash.now[:error] = @group.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      flash[:success] = 'Category was deleted successfully!'
      redirect_to groups_url
    else
      flash[:error] = @group.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:splash]

  def splash; end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @purchases = @group.purchases.order(id: :desc)
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = current_user.purchases.new(purchase_params.except(:group_ids))
    @groups = Group.where(id: purchase_params[:group_ids])
    if @groups.empty?
      flash.now[:error] = 'You must choose at least one category!'
      render :new
    elsif @purchase.save
      @groups.each do |group|
        group.purchases << @purchase
      end
      flash[:success] = "Transaction was created and added to #{@groups.length} goups!"
      redirect_to group_purchases_path(params[:group_id])
    else
      flash.now[:error] = @purchase.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @purchase = Purchase.find(params[:id])
  end

  def update
    @purchase = Purchase.find(params[:id])
    @groups = Group.where(id: purchase_params[:group_ids])
    if @groups.empty?
      flash.now[:error] = 'You must choose at least one category!'
      render :edit
    elsif @purchase.update(purchase_params.except(:group_ids))
      @purchase.groups.delete_all
      @groups.each do |group|
        group.purchases << @purchase unless group.purchases.include?(@purchase)
      end
      flash[:succes] = 'Transaction updated successfully!'
      redirect_to group_purchases_path(params[:group_id])
    else
      flash.now[:error] = @purchase.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    if @purchase.destroy
      flash[:success] = 'Transaction was deleted successfully!'
      redirect_to group_purchases_url(params[:group_id])
    else
      flash.now[:error] = @purchase.errors.full_messages.to_sentence
      render :show
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount, group_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_purchases_helper.rb
module GroupPurchasesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_amount(group)
    group.purchases.sum(:amount)
  end

  def check_url(url)
    default = 'no-pictures.png'
    if (File.extname(url) =~ /^(.png|.gif|.jpg)$/) || (url =~ /^#{URI::DEFAULT_PARSER.make_regexp}$/)
      url
    else
      default
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<header>
  <h1>Categories</h1>
</header>
<main class="g-bg">
  <section>
    <% if @groups.empty? %>
      <div class="empty">
        <p>Please add a new category</p>
      </div>
    <% end %>
    <ul class="category-list">
      <% @groups.each do |group| %>
        <% total_amount = total_amount(group) %>
        <li class="w-bg">
          <%= link_to group_purchases_url(group), data: { turbo: false }, class: 'item' do %>
            <div class="category-card">
              <div class="category-image-info">
                <%= image_tag(check_url(group.icon), class: 'icon', alt: 'group icon') %>
                <div class="category_info">
                  <span class="name"><%= group.name %></span>
                  <span class="date"><%= group.created_at.strftime('%d %b %Y') %></span>
                </div>
              </div>
              <div class="category-amount">
                <span class="amount">$<%= total_amount %></span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>
  <section class="button">
    <div class="button-border">
      <%= link_to "Add a Category", new_group_path, data: { turbo: false }  %>
    </div>
  </section>
</main>

app/views/groups/new.html.erb
<header>
  <%= link_to(image_tag('back.png', alt: 'Back'), groups_path, class: 'back-button') %>
  <h1>New Category</h1>
</header>
<main>
  <section>
    <%= form_with model: @group, class: "form" do |f| %>
      <div class="field">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name" %>
      </div>
      <div class="field">
        <%= f.text_field :icon, autofocus: true, autocomplete: "icon", value: 'default.png', placeholder: "Icon Link" %>
      </div>
      <div class="button">
        <div class="button-border">
          <%= f.submit "Add a Category", data: { turbo: false } %>
        </div>
      </div>
    <% end %>
  </section>
</main>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/splash.html.erb
<div class="splash-container">
  <div class="splash-appicon">
    <h1>BudgetLover</h1>
  </div>
  <div class="splash-buttons">
    <div class="login-button">
      <%= link_to "LOG IN", new_user_session_path, data: { turbo: false } %>
    </div>
    <div class="signup-button">
      <%= link_to "SIGN UP", new_user_registration_path, data: { turbo: false } %>
    </div>
  </div>
</div>

app/views/purchases/edit.html.erb
<h1>Purchases#edit</h1>
<p>Find me in app/views/purchases/edit.html.erb</p>

app/views/purchases/index.html.erb
<header>
  <%= link_to(image_tag('back.png', alt: 'Back'), groups_path, class: 'back-button') %>
  <h1>DETAILS</h1>
</header>
<main class="g-bg">
  <section class="w-bg">
    <% if @purchases.empty? %>
      <%= button_to "delete", {:controller => :groups, :action => 'destroy', :id => @group.id }, :method => :delete %>
    <% end %>
    <%= link_to group_purchases_url(@group), data: { turbo: false }, class: 'item' do %>
      <div class="category-card">
        <div class="category-image-info">
          <%= image_tag(check_url(@group.icon), class: 'icon', alt: 'group icon') %>
          <div class="category_info">
            <span class="name"><%= @group.name %></span>
          </div>
        </div>
      </div>
    <% end %>    
    <ul class="purchases-list">
      <% @purchases.each do |purchase| %>
        <li>
          <%= link_to group_purchase_url(@group, purchase) do %>
            <div class="purchase-details">
              <span><%= purchase.name %></span>
              <span>$<%= purchase.amount %></span>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="cagetory-total">
      <span>TOTAL PAYMENT</span>
      <span>$<%= total_amount(@group) %></span>
    </div>
  </section>
  <section class="button">
    <div class="button-border">
      <%= link_to "Add a Transaction", new_group_purchase_path %>
    </div>
  </section>
</main>

app/views/purchases/new.html.erb
<header>
  <%= link_to(image_tag('back.png', alt: 'Back'), group_purchases_path(params[:group_id]), class: 'back-button') %>
  <h1>New Transaction</h1>
</header>
<main class="g-bg">
  <section class="w-bg">
    <%= form_with(url: group_purchases_path, model: @purchase, class: "form") do |f| %>
      <div class="field">
        <%= f.text_field :name, autocomplete: "name", placeholder: "Name of service" %>
      </div>
      <div class="field">
        <%= f.text_field :amount, autocomplete: "amount", placeholder: "$10" %>
      </div>
      <div class="checkbox">
        <%= f.collection_check_boxes :group_ids, current_user.groups, :id, :name, :include_hidden => false %>
      </div>
      <div class="button">
        <div class="button-border">
          <%= f.submit "Add a Transaction", data: { turbo: false }, class: "btn"  %>
        </div>
      </div>
    <% end %>    
  </section>
</main>

app/views/purchases/show.html.erb
<header>
  <%= link_to(image_tag('back.png', alt: 'Back'), group_purchases_path(params[:group_id]), class: 'back-button') %>
  <h1>Details</h1>
</header>
<main>
  <section>
    <span><%= @purchase.name %></span>
    <span><%= @purchase.amount %></span>
  </section>
  <section>
    <%= link_to "edit", edit_group_purchase_path(params[:group_id], @purchase) %>
    <%= button_to "delete",  {:controller => :purchases, :action => 'destroy'}, method: :delete %>
  </section>
</main>